import pandas as pd
from typing import List, Dict, Any
import io
import streamlit as st

def load_css() -> None:
    """Load and inject custom styles.css into the page."""
    import os
    from pathlib import Path
    
    css_path = Path(__file__).resolve().parent.parent / "assets" / "styles.css"
    if css_path.exists():
        with open(css_path, "r", encoding="utf-8") as f:
            st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)
            
    # Inject light theme style adjustments if enabled
    if "theme" in st.session_state and st.session_state.theme == "Light":
        st.markdown(
            """
            <style>
            :root {
                --bg-dark: #f8fafc !important;
                --card-bg-dark: rgba(255, 255, 255, 0.85) !important;
                --text-dark: #0f172a !important;
                --border-color: rgba(0, 0, 0, 0.08) !important;
                --shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.05) !important;
            }
            .stApp {
                background-color: #f8fafc !important;
            }
            p, h1, h2, h3, h4, h5, h6, label, span, div.stMarkdown {
                color: #0f172a !important;
            }
            /* Keep button text white */
            div.stButton > button {
                color: white !important;
            }
            </style>
            """,
            unsafe_allow_html=True
        )

def export_to_csv(data: List[Dict[str, Any]]) -> bytes:
    """Convert list of dictionaries into CSV bytes for Streamlit download button."""
    if not data:
        return b""
    df = pd.DataFrame(data)
    csv_buffer = io.BytesIO()
    df.to_csv(csv_buffer, index=False)
    return csv_buffer.getvalue()

def format_date(date_str: str) -> str:
    """Format ISO date strings for better readability."""
    try:
        from datetime import datetime
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        return dt.strftime("%b %d, %Y")
    except Exception:
        return date_str

def generate_pdf_text_content(title: str, content: str, date_str: str) -> bytes:
    """
    Generate a simple textual PDF file content representing notice download.
    Using standard reportlab can be complex and requires external compilation,
    so we return a nicely formatted TXT file representation styled as a document
    as a robust download asset.
    """
    doc = f"""
=========================================================
               SMART CAMPUS NOTICE BOARD
=========================================================
Date: {format_date(date_str)}
Title: {title}
---------------------------------------------------------
Content:
{content}

---------------------------------------------------------
Generated by Smart Campus Management System Portal.
=========================================================
"""
    return doc.encode("utf-8")

